"""
В файле расположены основные константы размера и цвета
Автор: Озирный МАксим
"""

WIN_W_START = 650
WIN_H_START = 450
HEIGHT_INFO_FRAME = 130
WIDTH_FILR_FRAME = 200
MIN_WIDTH_FILR_FRAME = 150
MIN_SIZE_TABLE = 150
MIN_WIDTH_TABLE = 100
HEIGHT_ROW = 32
COLOR_BG_TITLE_TABLE = "#02a1dc"
COLOR_BG_EVENT_ROW = "#fff"
COLOR_BG_ODD_ROW = "#f5f7fa"
COLOR_BG_SELECT_ROW = "#dce8f2"
COLOR_BG_BOTTOM_BTN = "#4876a9"
COLOR_FG_BOTTOM_BTN = "#fff"
COLOR_TEXT_TITLE = "#fff"
COLOR_TEXT_TABLE = "#000"
COLOR_BG_LAST_CH = "#fff"
COLOR_BG_TITLE_LAST_CH = "#7B7C7C"
COLOR_BG_FRAME_TABLE = "#fff"
COLOR_BG_FRAME_FILTR = "#fff"
COLOR_FG_FRAME_TABLE = "#000"
COLOR_FG_FRAME_FILTR = "#000"
COLOR_BG_BTN_FILTR_TABLE = "#b2b2b2"
FONT_TITLE_FILTR = 28
PADX_FILTR_TABLE = 15
COLOR_BG_MENU = "#fff"
COLOR_FG_MENU = "#000"
FILTER_TAB_TEXT = "фильтр"
TABLES_TAB_TEXT = "поля"
LAST_CHANGES_CLOSED_TAB = "Последние изменения ↑"
LAST_CHANGES_OPENED_TAB = "Последние изменения ↓"
MENU_FILE_TEXT = "Файл"
MENU_CHANGE_TEXT = "Изменить"
MENU_REPORT_TEXT = "Отчёты"
DEFAULT_SEARCH_TEXT = "Найти"
CURSOR_CHANGE_WIGHT = "sb_h_double_arrow"
CURSOR_CHANGE_HEIGHT = "sb_v_double_arrow"

MAIN_BACKGROUND = "#f8f9fa"
